server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
        - id: campaign-service
          uri: lb://campaign-service
          predicates:
            - Path=/api/v1/campaigns/**
          filters:
            - StripPrefix=2
        - id: ad-service
          uri: lb://ad-service
          predicates:
            - Path=/api/v1/ads/**
          filters:
            - StripPrefix=2
        - id: publisher-service
          uri: lb://publisher-service
          predicates:
            - Path=/api/v1/publishers/**
          filters:
            - StripPrefix=2
        - id: data-collector-service
          uri: lb://data-collector-service
          predicates:
            - Path=/api/v1/events/**
          filters:
            - StripPrefix=2
        - id: batch-processing-service
          uri: lb://batch-processing-service
          predicates:
            - Path=/api/v1/batch/**
          filters:
            - StripPrefix=2
        - id: ad-recommendation-service
          uri: lb://ad-recommendation-service
          predicates:
            - Path=/api/v1/recommendations/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${JWKS_SERVICE_HOST:localhost}:${JWKS_SERVICE_PORT:8090}/oauth2/jwks

jwt:
  secret: your-super-secret-jwt-key-for-advertising-msa-2024
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일 (밀리초)

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    com.example.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${JWKS_SERVICE_HOST:jwks-service}:${JWKS_SERVICE_PORT:8090}/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true 