server:
  port: 8081

spring:
  application:
    name: campaign-service
  datasource:
    url: jdbc:mysql://campaign-db:3306/campaign_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: '!test'
    import: |
      optional:configserver:http://config-service:8888
      optional:consul:
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      uri: http://config-service:8888
      fail-fast: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://jwks-service:8090/oauth2/jwks

jwt:
  expiration: 86400000
  refresh-expiration: 604800000
  private-key-path: /app/keys/private_key.pem
  public-key-path: /app/keys/public_key.pem

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.campaign: DEBUG 