services:
  # Configuration Service
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    volumes:
      - ./config-service/target/config-service-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./config-service/src/main/resources/config:/app/config
    working_dir: /app
    command: java -jar app.jar
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    working_dir: /app
    command: java -jar app.jar
    depends_on:
      config-service:
        condition: service_healthy
      consul:
        condition: service_started
      user-service:
        condition: service_healthy
    networks:
      - msa-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Campaign Service
  campaign-service:
    build: ./campaign-service
    container_name: campaign-service
    ports:
      - "8081:8081"
    working_dir: /app
    command: java -jar app.jar
    depends_on:
      config-service:
        condition: service_healthy
      campaign-db:
        condition: service_healthy
      consul:
        condition: service_started
    networks:
      - msa-network
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=docker

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    working_dir: /app
    command: java -jar app.jar
    depends_on:
      config-service:
        condition: service_healthy
      user-db:
        condition: service_healthy
      consul:
        condition: service_started
    networks:
      - msa-network
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ad Service
  ad-service:
    build: ./ad-service
    container_name: ad-service
    ports:
      - "8083:8083"
    working_dir: /app
    command: java -jar app.jar
    depends_on:
      config-service:
        condition: service_healthy
      ad-db:
        condition: service_healthy
      consul:
        condition: service_started
    networks:
      - msa-network
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=docker

  # Publisher Service
  publisher-service:
    build: ./publisher-service
    container_name: publisher-service
    ports:
      - "8084:8084"
    working_dir: /app
    command: java -jar app.jar
    depends_on:
      config-service:
        condition: service_healthy
      publisher-db:
        condition: service_healthy
      consul:
        condition: service_started
    networks:
      - msa-network
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_PROFILES_ACTIVE=docker

  # MySQL Database (통합)
  mysql:
    image: mysql:8.0
    container_name: demo-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msa
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docs/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docs/sql:/docker-entrypoint-initdb.d/sql
    networks:
      - msa-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - msa-network

  # Ad DB
  ad-db:
    image: mysql:8.0
    container_name: demo-ad-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ad_db
    ports:
      - "3307:3306"
    volumes:
      - ./docs/sql/init-ad-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docs/sql:/docker-entrypoint-initdb.d/sql
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  campaign-db:
    image: mysql:8.0
    container_name: demo-campaign-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campaign_db
    ports:
      - "3308:3306"
    volumes:
      - ./docs/sql/init-campaign-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docs/sql:/docker-entrypoint-initdb.d/sql
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  publisher-db:
    image: mysql:8.0
    container_name: demo-publisher-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: publisher_db
    ports:
      - "3309:3306"
    volumes:
      - ./docs/sql/init-publisher-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docs/sql:/docker-entrypoint-initdb.d/sql
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # User DB
  user-db:
    image: mysql:8.0
    container_name: demo-user-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3310:3306"
    volumes:
      - ./docs/sql/init-user-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docs/sql:/docker-entrypoint-initdb.d/sql
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Consul for Service Discovery
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data
    volumes:
      - consul-data:/consul/data
    networks:
      - msa-network

  jwks-service:
    build: ./jwks-service
    container_name: jwks-service
    ports:
      - "8090:8090"
    working_dir: /app
    command: java -jar app.jar
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/oauth2/jwks"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=0S58ImIOSZuJok-yz94fCA
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - msa-network

volumes:
  mysql-data:
  consul-data:

networks:
  msa-network:
    driver: bridge 