spring:
  application:
    name: flink-apps
  config:
    activate:
      on-profile: '!test'
    import: |
      optional:configserver:http://config-service:8888
      optional:consul:
  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true
    consul:
      config:
        fail-fast: true

logging:
  level:
    com.example.advertising: DEBUG
    org.apache.flink: INFO
    org.springframework.cloud.config: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Flink 애플리케이션 기본 설정
flink:
  kafka:
    bootstrap-servers: localhost:9092
    click-topic: ad-clicks
    impression-topic: ad-impressions
    click-group-id: flink-click-processor
    impression-group-id: flink-impression-processor
  processing:
    click-window-seconds: 10
    impression-window-seconds: 10
    user-pattern-window-minutes: 5
    ctr-window-minutes: 1
    cpm-window-minutes: 1
    geographic-window-minutes: 5
  monitoring:
    enable-metrics: true
    metrics-prefix: flink.advertising
    metrics-interval-seconds: 30

---
spring:
  config:
    activate:
      on-profile: docker
    import: |
      optional:configserver:http://config-service:8888
      optional:consul:
  # ... 기존 설정 유지

# ... 기존 설정 유지 