server:
  port: 8085
  ssl:
    enabled: false
  tomcat:
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
    relaxed-query-chars: "|,{,},[,],\\"
    relaxed-path-chars: "|,{,},[,],\\"

spring:
  application:
    name: data-collector-service
  config:
    activate:
      on-profile: '!test'
    import:
      - "optional:configserver:http://${CONFIG_SERVICE_HOST:localhost}:${CONFIG_SERVICE_PORT:8888}"
    fail-fast: true
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      uri: http://${CONFIG_SERVICE_HOST:localhost}:${CONFIG_SERVICE_PORT:8888}
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: data-collector-service
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
        hostname: data-collector-service

---
spring:
  application:
    name: data-collector-service
  config:
    activate:
      on-profile: docker
    import:
      - "optional:configserver:http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8888}"
    fail-fast: true
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      uri: http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8888}
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: data-collector-service
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
        hostname: data-collector-service

# JWT 설정
jwt:
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일 (밀리초)


# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://${JWKS_SERVICE_HOST:localhost}:${JWKS_SERVICE_PORT:8090}/oauth2/jwks 