apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service
  namespace: advertising-msa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      containers:
      - name: campaign-service
        image: campaign-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://campaign-db:3306/campaigndb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "campaign"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: campaign-service
  namespace: advertising-msa
spec:
  selector:
    app: campaign-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP 