server:
  port: 8086

spring:
  application:
    name: data-processor-service
  config:
    activate:
      on-profile: '!test'
    import:
      - "optional:configserver:http://${CONFIG_SERVICE_HOST:localhost}:${CONFIG_SERVICE_PORT:8888}"
    fail-fast: true
  cloud:
    compatibility-verifier:
      enabled: false
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: data-processor-service
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
        hostname: data-processor-service

---
spring:
  application:
    name: data-processor-service
  config:
    activate:
      on-profile: docker
    import:
      - "optional:configserver:http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8888}"
    fail-fast: true
  cloud:
    compatibility-verifier:
      enabled: false
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: data-processor-service
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
        hostname: data-processor-service
    config:
      uri: http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8888} 