spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          enabled: false

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config: DEBUG 